version: "3.7"

services:
  sele-hub:
    container_name: sele-hub
    hostname: sele-hub
    image: selenium/hub:3.12.0-cobalt
    # network_mode: "host"
    # networks:
    #   sele-net:
    #     ipv4_address: 172.100.0.2
    ports:
      - 4444:4444

  sele-chrome:
    image: selenium/node-chrome-debug:3.12.0-cobalt
    # networks:
    #   sele-net:
    #     ipv4_address: 172.100.0.3
    ports:
      - 15900-15949:5900
    depends_on:
      - sele-hub
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=sele-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_ENV_no_proxy=localhost

  sele-firefox:
    image: selenium/node-firefox-debug:3.141.59-radium
    # networks:
    #   sele-net:
    #     ipv4_address: 172.100.0.4
    ports:
      - 15950-15999:5900
    depends_on:
      - sele-hub
    environment:
      - no_proxy=localhost
      - HUB_PORT_4444_TCP_ADDR=sele-hub
      - HUB_PORT_4444_TCP_PORT=4444
      - HUB_ENV_no_proxy=localhost

  4shamo:
    image: nobiki/4shamo:latest
    # build: .
    command: "/bootstrap.sh"
    volumes:
      - ${PWD}/tests/:/tests
      - ${PWD}/bootstrap.sh:/bootstrap.sh
    depends_on:
      - sele-hub
    tty: true


# networks:
#   sele-net:
#     driver: bridge
#     ipam:
#       driver: default
#       config:
#         - subnet: 172.100.0.0/16
