version: "3.7"

services:
  sele-hub:
    container_name: sele-hub
    hostname: sele-hub
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    environment:
      - TZ=Asia/Tokyo
    init: true

  sele-chrome:
    image: sele-chrome
    build:
      context: .
      dockerfile: docker/chrome.Dockerfile
    ports:
      - 15901-1590${SCALE}:5900
    depends_on:
      - sele-hub
    env_file: docker/node.env
    init: true

  sele-firefox:
    image: sele-firefox
    build:
      context: .
      dockerfile: docker/firefox.Dockerfile
    ports:
      - 15801-1580${SCALE}:5900
    depends_on:
      - sele-hub
    env_file: docker/node.env
    init: true

  gpu-chrome:
    image: gpu-chrome
    build:
      context: .
      dockerfile: docker/gpu-chrome.Dockerfile
    # ports:
    #   - 15701-1570${SCALE}:5900
    # depends_on:
    #   - sele-hub
    # env_file: docker/node.env
    # init: true

  4shamo:
    build:
      context: .
      dockerfile: docker/4shamo.Dockerfile
    command: "/bootstrap.sh"
    volumes:
      - ${PWD}/tests/:/tests
      - ${PWD}/bootstrap.sh:/bootstrap.sh
    depends_on:
      - sele-hub
    tty: true
    init: true

