version: "3"

services:
  grid-hub:
    container_name: grid-hub
    hostname: grid-hub
    image: selenium/hub:3.141.59
    ports:
      - 4444:4444
    environment:
      - TZ=Asia/Tokyo

  grid-chrome:
    # container_name: grid-chrome
    # hostname: grid-chrome
    # image: selenium/node-chrome-debug:3.12.0-cobalt
    image: grid-chrome
    build:
      context: .
      dockerfile: chrome.Dockerfile
    ports:
      - 15901-1590${SCALE}:5900
    depends_on:
      - grid-hub
    env_file: .env
    extra_hosts:
      - bell-face.local:172.18.0.2
      - user.bell-face.local:172.18.0.2
      - api.bell-face.local:172.18.0.2
      - presentation.bell-face.localocal:172.18.0.2
      - popup.bell-face.localocal:172.18.0.2
      - node1.bell-face.localocal:172.18.0.2
      - user.best-mtg.localocal:172.18.0.2
      - best-mtg.localocal:172.18.0.2

  grid-firefox:
    # container_name: grid-firefox
    # hostname: grid-firefox
    # image: selenium/node-firefox-debug:3.141.59-radium
    image: grid-firefox
    build:
      context: .
      dockerfile: firefox.Dockerfile
    ports:
      - 15801-1580${SCALE}:5900
    depends_on:
      - grid-hub
    env_file: .env
    extra_hosts:
      - bell-face.local:172.18.0.2
      - user.bell-face.local:172.18.0.2
      - api.bell-face.local:172.18.0.2
      - presentation.bell-face.localocal:172.18.0.2
      - popup.bell-face.localocal:172.18.0.2
      - node1.bell-face.localocal:172.18.0.2
      - user.best-mtg.localocal:172.18.0.2
      - best-mtg.localocal:172.18.0.2

